services:
  plantai:
    build: .
    container_name: plantai
    ports:
      - "5000:5000"
    environment:
      - YANDEX_DISK_TOKEN=${YANDEX_DISK_TOKEN}
    volumes:
      - ./static:/app/static
      - ./ml_models:/app/ml_models
    restart: unless-stopped